---
- hosts: clients
  gather_facts: no
  serial: 8
  tasks:

  - name: Create facts folder in current directory
    local_action: 
        module: ansible.builtin.file
        path: "{{ lookup('env', 'PWD') }}/facts"
        state: directory
        #owner: "{{ hostvars['ryan9'].local_user  }}"
        #group: "{{ hostvars['ryan9'].local_group }}"
        owner: "{{ lookup('env', 'USER') }}"
        mode: 0750

  - name: Collect only facts returned by facter
    ansible.builtin.setup:
      gather_subset:
        - '!all'
        - system
        - architecture
        - all_ipv4_addresses
        - all_ipv6_addresses
        - facter
    register: facts_result
    
  - name: Remove the previous fact files
    local_action: 
        module: file
        path: "{{ lookup('env', 'PWD') }}/facts/{{ facts_result }}"
        state: absent

  - name: Create current facts files
    local_action: 
      module: ansible.builtin.copy
      content: "{{ facts_result | to_nice_json }}"
      dest: "{{ lookup('env', 'PWD') }}/facts/{{ inventory_hostname }}.json"
      #owner: "{{ hostvars['ryan9'].local_user  }}"
      #group: "{{ hostvars['ryan9'].local_group }}"
      owner: "{{ lookup('env', 'USER') }}"
      mode: 0664
