---

- name: Install basic packages (more later)
  #hosts: clients
  hosts: test

  tasks:
  
  - name: "Basic Member Packages"
    ansible.builtin.apt:
      update_cache: true
      pkg:
      - vim
      - sudo
      - gpg
      - openssl
      - htop
      - tree
      - curl
      - socat
      - sudo
      - gpg
      - wget
      - ca-certificates 
      - net-tools
    become: true
