---

- name: get services
  hosts: ryan9
  tasks:

  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Print service facts
    ansible.builtin.debug:
        var: ansible_facts.services