---
- name: "Configure Metric Collectors"
  hosts: metric_collectors
  
  vars:
    influxdb_operators_token: ""
    influxdb_reload: false
    loki_force_reload: false

  roles:

    - nfs-client
    - influxdb
    - telegraf
