---

#
# https://github.com/grafana/grafana-ansible-collection/tree/main?tab=readme-ov-file
#
collections:
  - name: grafana.grafana
    version: 1.0.0
  - name: ansible.posix
  - name: community.general
  - name: community.crypto

