---
- name: "Configure Monitor2"
  hosts: monitor2
  
  vars:
    influx_force_reload: false
    influx_force_configure: false
    loki_force_reload: false

  roles:
    
    - influxdb
    - telegraf
    - loki
    - alloy
