---
#  When I move the cloud server, I don't need everything.
#  What I do need is a mail service, this is an attempt to wean off ISPConfig 

- name: "Service: mailsvc"
  hosts: mail_servers
  become: true
  vars:
    mysql_password: ""
    mariadb_security: true

    # PostfixAdmin admin setup for instance
    # mailsvc_create_admin: true 

    # Database configuration
    # mailsvc_mysql_root_password: ''  # Must be provided in inventory

  roles:
    #- mariadb
    - mailsvc
