---
- name: "Configure Monitor2"
  hosts: monitor2
  
  vars:
    influxdb_reload: true
    influxdb_configure: true
    loki_force_reload: false

  roles:
    
    - influxdb
    - loki

    - telegraf
    - alloy
