---
- name: "Service: mariadb"
  hosts: mariadb_servers
  become: true
  vars:
    mysql_password: ""
    mariadb_security: true
    mysql_users:
      - user: app_user
        password: ''
      - user: app_user1
        password: ''
      - user: backup_user
        password: 'foo!23#lbar'
  roles:
    - mariadb
