---
#  This is a pure testing system.  No DNS, no external connections
#  Tried LXC...access issues.
#  Come back to this...fix the ip address and start hardening.

- name: "Configure Monitor2"
  hosts: monitor2

  vars:
    influxdb_reload: true
    influxdb_configure: true
    loki_force_reload: false

  roles:
    - influxdb
    # - loki

    - telegraf
    # - alloy
